spring:
  datasource:
    ##url: jdbc:mysql://host.docker.internal:3306/ecommerce?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    url: jdbc:mysql://localhost:3307/ecommerce?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081
myapp:
  greeting: "Hello from Config Server!"
customer:
  default-name: "John Doe!"
  max-orders: 15
  greeting: "Welcome to Customer Service!"
