spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:ecommerce
    driver-class-name: org.h2.Driver
    username: sa
    password: password

server:
  port: 8081
myapp:
  greeting: "Hello from Config Server!"
customer:
  default-name: "John Doe!"
  max-orders: 15
  greeting: "Welcome to Customer Service!"
