spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:ecommerce
    driver-class-name: org.h2.Driver
    username: sa
    password: password

server:
  port: 8082
myapp:
  greeting: "Hello from Order Service!!!!"
